# Our First NumPy Array
In this chapter, we're going to dive into the world of baseball. Along the way, you'll get comfortable with the basics of `numpy`, a powerful package to do data science.

A list baseball has already been defined in the Python script, representing the height of some baseball players in centimeters. Can you add some code here and there to create a numpy array from it?

In [2]:
import numpy as np

In [3]:
# Create list baseball
baseball = [180, 215, 210, 210, 188, 176, 209, 200]

# Create a numpy array from baseball: np_baseball
np_baseball = np.array(baseball)

# Print out type of np_baseball
print(type(np_baseball))

<class 'numpy.ndarray'>


You are a huge baseball fan. You decide to call the MLB (Major League Baseball) and ask around for some more statistics on the height of the main players. They pass along data on more than a thousand players, which is stored as a regular Python list: `height_in`. The height is expressed in inches. Can you make a numpy array out of it and convert the units to meters?

In [4]:
weight_lb = [180, 215, 210, 210, 188, 176, 209, 200, 231, 180, 188, 180, 185,
             160, 180, 185, 197, 189, 185, 219, 230, 205, 230, 195, 180, 192,
             225, 203, 195, 182, 188, 200, 180, 200, 200, 245, 240, 215, 185,
             175, 199, 200, 215, 200, 205, 206, 186, 188, 220, 210, 195, 244,
             195, 200, 200, 212, 224, 210, 205, 220, 195, 200, 260, 228, 270,
             200, 210, 190, 220, 180, 205, 210, 220, 211, 200, 180, 190, 170,
             230, 155, 185]

len(weight_lb)

81

In [5]:
height_in = [74, 72, 72, 73, 69, 69, 71, 76, 71, 73, 73, 74, 74, 69, 70, 72, 73,
             75, 78, 79, 76, 74, 76, 72, 71, 75, 77, 74, 73, 74, 78, 73, 75, 73,
             75, 75, 74, 69, 71, 74, 73, 73, 76, 74, 74, 70, 72, 77, 74, 70, 76,
             75, 73, 75, 76, 76, 78, 74, 74, 76, 77, 81, 78, 75, 77, 75, 76, 74,
             72, 72, 75, 73, 73, 73, 70, 70, 70, 76, 68, 71, 72]

len(height_in)

81

In [6]:
# Create a numpy array from height: np_height_in
np_height_in = np.array(height_in)

# Convert np_height to m: np_height_m
np_height_m = 0.0254 * np_height_in

# Print np_height_m
print(np_height_m)

[1.8796 1.8288 1.8288 1.8542 1.7526 1.7526 1.8034 1.9304 1.8034 1.8542
 1.8542 1.8796 1.8796 1.7526 1.778  1.8288 1.8542 1.905  1.9812 2.0066
 1.9304 1.8796 1.9304 1.8288 1.8034 1.905  1.9558 1.8796 1.8542 1.8796
 1.9812 1.8542 1.905  1.8542 1.905  1.905  1.8796 1.7526 1.8034 1.8796
 1.8542 1.8542 1.9304 1.8796 1.8796 1.778  1.8288 1.9558 1.8796 1.778
 1.9304 1.905  1.8542 1.905  1.9304 1.9304 1.9812 1.8796 1.8796 1.9304
 1.9558 2.0574 1.9812 1.905  1.9558 1.905  1.9304 1.8796 1.8288 1.8288
 1.905  1.8542 1.8542 1.8542 1.778  1.778  1.778  1.9304 1.7272 1.8034
 1.8288]


# Create new arrays

Let's use numpy to create a new array: `bmi`

\begin{equation*}
BMI = \frac{weight(kg)}{height(m)^2}
\end{equation*}

In [7]:
# height and weight are available as regular lists

# Create array from height_in with metric units: np_height_m
np_height_m = np.array(height_in) * 0.0254

# Create array from weight_lb with metric units: np_weight_kg
np_weight_kg = np.array(weight_lb) * 0.453592

# Calculate the BMI: bmi
bmi = np_weight_kg / np_height_m**2

# Print out bmi
print(bmi)

[23.11037639 29.15891904 28.48080465 27.70585312 27.76243923 25.99036864
 29.14926052 24.34449467 32.21760373 23.7478741  24.80333518 23.11037639
 23.75233129 23.62760785 25.82702472 25.09023267 25.99072888 23.62311861
 21.37865979 24.67106431 27.99616887 26.32015089 27.99616887 26.44646146
 25.10462629 23.99808874 26.68081066 26.06336893 25.72686361 23.36715835
 21.72534076 26.38652678 22.4982082  26.38652678 24.99800911 30.62256116
 30.81383519 31.74959805 25.80197702 22.46842149 26.25459415 26.38652678
 26.17033177 25.67819599 26.32015089 29.55759495 25.22585554 22.29329957
 28.24601559 30.13152883 23.73588231 30.49757111 25.72686361 24.99800911
 24.34449467 25.80516435 25.88551239 26.96210579 26.32015089 26.77894414
 23.12336924 21.43176364 30.04568402 28.49773038 32.01697279 24.99800911
 25.56171941 24.39428619 29.83703344 24.41211827 25.62295933 27.70585312
 29.02517946 27.83778576 28.69669413 25.82702472 27.26185942 20.69282047
 34.97099295 21.61787263 25.09023267]


# Subset

To subset both regular Python lists and numpy arrays, you can use square brackets:

`x = [4 , 9 , 6, 3, 1]
x[1]`

`import numpy as np
y = np.array(x)
y[1]`

For numpy specifically, you can also use boolean numpy arrays:

`high = y > 5
y[high]`

In [10]:
# Calculate the BMI: bmi
np_height_m = np.array(height_in) * 0.0254
np_weight_kg = np.array(weight_lb) * 0.453592
bmi = np_weight_kg / np_height_m ** 2

# Create the light array
light = bmi < 21

# Print out light
light

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False,  True, False, False, False])

In [11]:
# Print out BMIs of all baseball players whose BMI is below 21
bmi[light]

array([20.69282047])

In [12]:
# Create arrays
my_house = np.array([18.0, 20.0, 10.75, 9.50])
your_house = np.array([14.0, 24.0, 14.25, 9.0])

# my_house greater than or equal to 18
print(my_house >=18)

# my_house less than your_house
print(my_house < your_house)

[ True  True False False]
[False  True  True False]


In [13]:
# Booleans
my_house = np.array([18.0, 20.0, 10.75, 9.50])
your_house = np.array([14.0, 24.0, 14.25, 9.0])

# my_house greater than 18.5 or smaller than 10
print(np.logical_or(my_house > 18.5, my_house < 10))

# Both my_house and your_house smaller than 11
print(np.logical_and(my_house < 11, your_house < 11))

[False  True False  True]
[False False False  True]


In [14]:
# Store weight and height lists as numpy arrays
np_weight_lb = np.array(weight_lb)
np_height_in = np.array(height_in)

# Print out the weight at index 50
print(np_weight_lb[50])

# Print out sub-array of np_height
print(np_height_in[50:52])

195
[76]


# Numpy and types

First of all, numpy arrays cannot contain elements with different types. If you try to build such a list, some of the elements' types are changed to end up with a homogeneous list. This is known as **type coercion**.

Second, the typical arithmetic operators, such as `+`, `-`, `*` and `/` have a different meaning for regular Python lists and numpy arrays.

# Your First 2D NumPy Array
Before working on the actual MLB data, let's try to create a 2D numpy array from a small list of lists.
In this exercise, `baseball` is a list of lists. The main list contains 4 elements. Each of these elements is a list containing the height and the weight of 4 baseball players, in this order. baseball is already coded for you in the script.

In [57]:
# Create baseball, a list of lists
baseball = [[180, 78.4],
            [215, 102.7],
            [210, 98.5],
            [188, 75.2]]

# Create a 2D numpy array from baseball: np_baseball
np_baseball = np.array(baseball)

# Print out the type of np_baseball
print(type(np_baseball))

# Print out the shape of np_baseball
print(np_baseball.shape)

<class 'numpy.ndarray'>
(4, 2)


# Subsetting 2D NumPy Arrays
If your 2D numpy array has a regular structure, i.e. each row and column has a fixed number of values, complicated ways of subsetting become very easy. Have a look at the code below where the elements "a" and "c" are extracted from a list of lists.

## regular list of lists

`x = [["a", "b"], ["c", "d"]]`

`[x[0][0], x[1][0]]`

## numpy

`import numpy as np
np_x = np.array(x)
np_x[:,0]`

For regular Python lists, this is a real pain. For 2D numpy arrays, however, it's pretty intuitive! The indexes before the comma refer to the rows, while those after the comma refer to the columns. The `:` is for slicing; in this example, it tells Python to include all rows.

The code that converts the pre-loaded baseball list to a 2D numpy array is already in the script. The first column contains the players' height in inches and the second column holds player weight, in pounds. Add some lines to make the correct selections. Remember that in Python, the first element is at index 0!

In [62]:
# Create np_baseball (2 cols)
np_baseball = np.array(baseball)

# Print out the 3rd row of np_baseball
print(np_baseball[3,:])

# Select the entire second column of np_baseball: np_weight_lb
np_weight_lb = np_baseball[:,1]
print(np_weight_lb)

# Print out height of 124th player
print(np_weight_lb[2:])

[188.   75.2]
[ 78.4 102.7  98.5  75.2]
[98.5 75.2]


Remember how you calculated the Body Mass Index for all baseball players? numpy was able to perform all calculations element-wise (i.e. element by element). For 2D numpy arrays this isn't any different! You can combine matrices with single numbers, with vectors, and with other matrices.

In [64]:
np_mat = np.array([[1, 2],
                   [3, 4],
                   [5, 6]])

print(np_mat * 2)
print()

# broadcast
print(np_mat + np.array([10, 10]))
print()
print(np_mat + np_mat)

[[ 2  4]
 [ 6  8]
 [10 12]]

[[11 12]
 [13 14]
 [15 16]]

[[ 2  4]
 [ 6  8]
 [10 12]]


# Statistics with numpy
The baseball data is available as a 2D numpy array with 2 columns (height, weight) and 82 rows. The name of this numpy array is `np_baseball`. After restructuring the data, however, you notice that some height values are abnormally high. Follow the instructions and discover which summary statistic is best suited if you're dealing with so-called outliers.

In [13]:
baseball = [(74, 180), (72, 215), (72, 210), (73, 210), (69, 188), (69, 176), (71, 209), (76, 200),
             (71, 231), (73, 180), (73, 188), (74, 180), (74, 185), (69, 160), (70, 180), (72, 185),
             (73, 197), (75, 189), (78, 185), (79, 219), (76, 230), (74, 205), (76, 230), (72, 195),
             (71, 180), (75, 192), (77, 225), (74, 203), (73, 195), (74, 182), (78, 188), (73, 200),
             (75, 180), (73, 200), (75, 200), (75, 245), (74, 240), (69, 215), (71, 185), (74, 175),
             (73, 199), (73, 200), (76, 215), (74, 200), (74, 205), (70, 206), (72, 186), (77, 188),
             (74, 220), (70, 210), (76, 195), (75, 244), (73, 195), (75, 200), (76, 200), (76, 212),
             (78, 224), (74, 210), (74, 205), (76, 220), (77, 195), (81, 200), (78, 260), (75, 228),
             (77, 270), (75, 200), (76, 210), (74, 190), (72, 220), (72, 180), (75, 205), (73, 210),
             (73, 220), (73, 211), (70, 200), (70, 180), (7000, 190), (76, 170), (68, 230), (71, 155),
             (72, 185)]

In [16]:
# Create np_height_in from np_baseball
np_baseball = np.array(baseball)

np_height_in = np.array(np_baseball[:,0])

# Print out the mean of np_height_in
print('Mean:',np.mean(np_height_in))

# Print out the median of np_height_in
print('Median:', np.median(np_height_in))

Mean: 159.25925925925927
Median: 74.0


In [3]:
import numpy as np
baseball = [(74, 180), (72, 215), (72, 210), (73, 210), (69, 188), (69, 176), (71, 209), (76, 200),
             (71, 231), (73, 180), (73, 188), (74, 180), (74, 185), (69, 160), (70, 180), (72, 185),
             (73, 197), (75, 189), (78, 185), (79, 219), (76, 230), (74, 205), (76, 230), (72, 195),
             (71, 180), (75, 192), (77, 225), (74, 203), (73, 195), (74, 182), (78, 188), (73, 200),
             (75, 180), (73, 200), (75, 200), (75, 245), (74, 240), (69, 215), (71, 185), (74, 175),
             (73, 199), (73, 200), (76, 215), (74, 200), (74, 205), (70, 206), (72, 186), (77, 188),
             (74, 220), (70, 210), (76, 195), (75, 244), (73, 195), (75, 200), (76, 200), (76, 212),
             (78, 224), (74, 210), (74, 205), (76, 220), (77, 195), (81, 200), (78, 260), (75, 228),
             (77, 270), (75, 200), (76, 210), (74, 190), (72, 220), (72, 180), (75, 205), (73, 210),
             (73, 220), (73, 211), (70, 200), (70, 180), (70, 190), (76, 170), (68, 230), (71, 155),
             (72, 185)]

# Create np_height_in from np_baseball
np_baseball = np.array(baseball)
np_height_in = np.array(np_baseball)[:,0]
print('media:',np.mean(np_height_in))
print('mediana:',np.median(np_height_in))

media: 73.70370370370371
mediana: 74.0


# Explore the baseball data
Because the mean and median are so far apart, you decide to complain to the MLB. They find the error and send the corrected data over to you. It's again available as a 2D Numpy array `np_baseball`, with three columns.

The Python script on the right already includes code to print out informative messages with the different summary statistics. Can you finish the job?

In [18]:
# Print mean height (first column)
avg = np.mean(np_baseball[:,0])
print("Average: " + str(avg))

Average: 159.25925925925927


In [20]:
# Print median height. Replace 'None'
med = np.median(np_baseball[:,0])
print("Median: " + str(med))

Median: 74.0


In [21]:
# Print out the standard deviation on height. Replace 'None'
stddev = np.std(np_baseball[:,0])
print("Standard Deviation: " + str(stddev))

Standard Deviation: 764.8223028958156


In [23]:
# Print out correlation between first and second column. Replace 'None'
corr = np.corrcoef(np_baseball[:,0], np_baseball[:,1])
print("Correlation: \n" + str(corr))

Correlation: 
[[ 1.         -0.06470339]
 [-0.06470339  1.        ]]


# LOOPS OVER NUMPY ARRAYS

In [4]:
# For loop over np_height
for x in np_height_in: 
    print (str(x)+" pulgadas")

# For loop over np_baseball
for y in np.nditer(np_baseball):
    print(y)

74 pulgadas
72 pulgadas
72 pulgadas
73 pulgadas
69 pulgadas
69 pulgadas
71 pulgadas
76 pulgadas
71 pulgadas
73 pulgadas
73 pulgadas
74 pulgadas
74 pulgadas
69 pulgadas
70 pulgadas
72 pulgadas
73 pulgadas
75 pulgadas
78 pulgadas
79 pulgadas
76 pulgadas
74 pulgadas
76 pulgadas
72 pulgadas
71 pulgadas
75 pulgadas
77 pulgadas
74 pulgadas
73 pulgadas
74 pulgadas
78 pulgadas
73 pulgadas
75 pulgadas
73 pulgadas
75 pulgadas
75 pulgadas
74 pulgadas
69 pulgadas
71 pulgadas
74 pulgadas
73 pulgadas
73 pulgadas
76 pulgadas
74 pulgadas
74 pulgadas
70 pulgadas
72 pulgadas
77 pulgadas
74 pulgadas
70 pulgadas
76 pulgadas
75 pulgadas
73 pulgadas
75 pulgadas
76 pulgadas
76 pulgadas
78 pulgadas
74 pulgadas
74 pulgadas
76 pulgadas
77 pulgadas
81 pulgadas
78 pulgadas
75 pulgadas
77 pulgadas
75 pulgadas
76 pulgadas
74 pulgadas
72 pulgadas
72 pulgadas
75 pulgadas
73 pulgadas
73 pulgadas
73 pulgadas
70 pulgadas
70 pulgadas
70 pulgadas
76 pulgadas
68 pulgadas
71 pulgadas
72 pulgadas
74
180
72
215
72
210
73
210


Blend it all together
In the last few exercises you've learned everything there is to know about heights and weights of baseball players. Now it's time to dive into another sport: soccer.

You've contacted FIFA for some data and they handed you two lists. The lists are the following:

`positions = ['GK', 'M', 'A', 'D', ...]`

`heights = [191, 184, 185, 180, ...]`

Each element in the lists corresponds to a player. The first list, positions, contains strings representing each player's position. The possible positions are: 'GK' (goalkeeper), 'M' (midfield), 'A' (attack) and 'D' (defense). The second list, heights, contains integers representing the height of the player in cm. The first player in the lists is a goalkeeper and is pretty tall (191 cm).

You're fairly confident that the median height of goalkeepers is higher than that of other players on the soccer field. Some of your friends don't believe you, so you are determined to show them using the data you received from FIFA and your newly acquired Python skills.

In [17]:
import numpy as np
fifa = np.array([[69, 'GK', 191, ' Right'],
                   [64, 'GK', 193, ' Right'],
                   [65, 'GK', 190, ' Right'],
                   [67, 'D', 178, ' Right'],
                   [61, 'GK', 185, ' Right'],
                   [62, 'D', 185, ' Right'],
                   [76, 'D', 193, ' Right'],
                   [63, 'M', 183, ' Right'],
                   [72, 'A', 184, ' Right'],
                   [72, 'M', 178, ' Left'],
                   [63, 'D', 180, ' Right'],
                   [73, 'M', 177, ' Right'],
                   [70, 'GK', 188, ' Right'],
                   [64, 'M', 177, ' Right'],
                   [65, 'GK', 187, ' Right'],
                   [75, 'A', 186, ' Left'],
                   [74, 'D', 183, ' Right'],
                   [70, 'GK', 189, ' Right'],
                   [78, 'A', 179, ' Right'],
                   [66, 'GK', 196, ' Right'],
                   [75, 'GK', 190, ' Right'],
                   [67, 'GK', 189, ' Right'],
                   [71, 'GK', 188, ' Right'],
                   [70, 'A', 188, ' Right']])

separar_posiciones= np.array(fifa[:,1]) #los dos puntos de un lado de la coma  me agarra todas las filas o todas las columnas

separar_alturas= np.array(fifa[:,2]).astype(np.float)
                          
altura_arqueros=separar_alturas[separar_posiciones == 'GK'] 
altura_elresto=separar_alturas[separar_posiciones !='']                          
print('altura media de los arqueros es :' + str (np.median(altura_arqueros)))                          

altura media de los arqueros es :189.0


In [6]:
fifa = np.array([[69, 'GK', 191, ' Right'],
                   [64, 'GK', 193, ' Right'],
                   [65, 'GK', 190, ' Right'],
                   [67, 'D', 178, ' Right'],
                   [61, 'GK', 185, ' Right'],
                   [62, 'D', 185, ' Right'],
                   [76, 'D', 193, ' Right'],
                   [63, 'M', 183, ' Right'],
                   [72, 'A', 184, ' Right'],
                   [72, 'M', 178, ' Left'],
                   [63, 'D', 180, ' Right'],
                   [73, 'M', 177, ' Right'],
                   [70, 'GK', 188, ' Right'],
                   [64, 'M', 177, ' Right'],
                   [65, 'GK', 187, ' Right'],
                   [75, 'A', 186, ' Left'],
                   [74, 'D', 183, ' Right'],
                   [70, 'GK', 189, ' Right'],
                   [78, 'A', 179, ' Right'],
                   [66, 'GK', 196, ' Right'],
                   [75, 'GK', 190, ' Right'],
                   [67, 'GK', 189, ' Right'],
                   [71, 'GK', 188, ' Right'],
                   [70, 'A', 188, ' Right']])
# Convert positions and heights to numpy arrays: np_positions, np_heights
np_positions = np.array(fifa[:,1])
np_heights = np.array(fifa[:,2]).astype(np.float)

# Heights of the goalkeepers: gk_heights
gk_heights = np_heights[np_positions == 'GK']

# Heights of the other players: other_heights
other_heights = np_heights[np_positions != 'GK']

# Print out the median height of goalkeepers. Replace 'None'
print("Median height of goalkeepers: " + str(np.median(gk_heights)))

Median height of goalkeepers: 189.0


In [30]:
# Print out the median height of other players. Replace 'None'
print("Median height of other players: " + str(np.median(other_heights)))

Median height of other players: 183.0
